<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha.1</VersionSuffix>
    <Product>SadGBA</Product>
    <Authors>kadu04t</Authors>
    <Copyright>Copyright (c) 2026 kadu04t</Copyright>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>

